version: '3'

services:
  dev:
    image: maven:3-eclipse-temurin-17-alpine
    volumes:
    - .:/ws
    - $HOME/.m2:/root/.m2
    working_dir: /ws
    entrypoint: sh -c 'apk update && apk add graphviz && (cd food-ordering-system && mvn clean com.github.ferstl:depgraph-maven-plugin:aggregate -DcreateImage=true -DreduceEdges=false -Dscope=compile "-Dincludes=com.food.ordering.system*:*" && ../watch.sh . test); tail -f'
